Clusters:
- Input:
    Kafka:
      Name: gostash
      Brokers:
        - "1xxx:xxx"
      Topics:
        - xxx
      Group: go_stash_core
      Consumers: 48
  Filters:
    - Action: timestamp
      Field: Timestamp
  Output:
    ElasticSearch:
      Username: xxx
      Password: xxx
      Hosts:
        - http://9.139.3.6:xx
      Index: "core_monitor_metrics-{{YYYYMMdd.HH}}"
